### ISSUE TITLE
Error generated

### ISSUE THREAD

**Issue by trondulseth** [haydenbleasel/gulp-favicons#10]
I'm trying to use favicons, but I only get an error. Am I doing something wrong - or is something up with the favicon plugin (or some other part of gulp)?

Here is my code from the gulpfile.js

```javascript
gulp.task('html', function() {
    return gulp.src('./mySpa.Frontend/src/index.htm')
        .pipe(htmlreplace({
            'css': 'css.css',
            'js': 'scripts.js'
        }))
        .pipe(favicons({
            files: { src: './mySpa.Frontend/src/images/logo.png', dest: './mySpa.Frontend/dist/icons/' },
            settings: { background: '#1d1d1d' }
        }))
        .pipe(gulp.dest('./mySpa.Frontend/dist/'));
});
```
And here is the error it generates when I try to run it
```javascript
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at DestroyableTransform.EventEmitter.emit (events.js:74:15)
    at DestroyableTransform.onerror (/Users/trondulsethamerika/Sites/mySpa/node_modules/gulp-html-replace/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.EventEmitter.emit (events.js:95:17)
    at onwriteError (/Users/trondulsethamerika/Sites/mySpa/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:10)
    at onwrite (/Users/trondulsethamerika/Sites/mySpa/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:353:5)
    at WritableState.onwrite (/Users/trondulsethamerika/Sites/mySpa/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:113:5)
    at afterTransform (/Users/trondulsethamerika/Sites/mySpa/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:84:5)
    at TransformState.afterTransform (/Users/trondulsethamerika/Sites/mySpa/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at /Users/trondulsethamerika/Sites/mySpa/node_modules/gulp-favicons/index.js:129:28
```

**Comment by haydenbleasel** [comment]
Hey @trondulseth, the version of `favicons` and `gulp-favicons` should fix up all these issues. Open up a new issue if you find something is broken :)
