### ISSUE TITLE
Uncaught, unspecified error event, events.js:87

### ISSUE THREAD

**Issue by iforwms** [haydenbleasel/gulp-favicons#11]
Here's the function and console log.

    gulp.task('favicons', function() {
      gulp.src('build/index.html')
         .pipe($.favicons({
            files: { src: 'src/img/favicon.png', dest: 'build/images/favicons/', },
            settings: { logging: true },
         }))
         .pipe(gulp.dest('build/images/favicons'));
    });

Console log: 

    [14:24:44] Using gulpfile D:\dropbox\work\gulp-master\gulpfile.js
    [14:24:44] Starting 'favicons'...
    [14:24:45] Finished 'favicons' after 550 ms

    Setting icons...
    Favicons source is an inline string...
    Encoded to base64: src/img/favicon.png...

    Generating favicons...
    Created folder: D:\dropbox\work\gulp-master\build\build\images\favicons\...
    Posted request to RealFaviconGenerator...
    events.js:87
          throw Error('Uncaught, unspecified "error" event.');
                ^
    Error: Uncaught, unspecified "error" event.
        at Error (native)
        at DestroyableTransform.emit (events.js:87:13)
        at DestroyableTransform.onerror (D:\dropbox\work\gulp-master\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:558:12)
        at DestroyableTransform.emit (events.js:107:17)
        at onwriteError (D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:335:10)
        at onwrite (D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:353:5)
        at WritableState.onwrite (D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:113:5)
        at afterTransform (D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:84:5)
        at TransformState.afterTransform (D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:59:12)
        at D:\dropbox\work\gulp-master\node_modules\gulp-favicons\index.js:129:28
        at D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\favicons\index.js:58:31
        at D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:541:30
        at D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\favicons\index.js:37:28
        at D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\favicons\index.js:113:28
        at D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\favicons\index.js:92:24
        at Object.ConnectManager.handleResponse (D:\dropbox\work\gulp-master\node_modules\gulp-favicons\node_modules\favicons\node_modules\node-rest-client\lib\node-rest-client.js:435:5)

**Comment by JoshuaLuckers** [comment]
@haydenbleasel are you aware of this issue?

**Comment by haydenbleasel** [comment]
Hey guys. Not aware of the issue yet as I haven't had any time to look into it lately. If you're good at debugging, perhaps you could check it out?

**Comment by JoshuaLuckers** [comment]
I figured out that I was using an image that didn't meet the size criteria. The image that's going to be used to generate the favicon must be 300x300 in size.

**Comment by haydenbleasel** [comment]
That's a really were limitation, it should be like 1500x1500 for OpenGraph. Wonder why it's limiting like that...

**Comment by bencooling** [comment]
I'm experiencing same issue. When I did a quick console.log I could see: 
`statusMessage: 'Cannot generate anything for ios. Master picture should be at least 57x57 but is only 47x47`

**Comment by haydenbleasel** [comment]
@bencooling Okay so your image is `47x47` but you need `57x57` or above to generate an iOS image. Did you opt-in for an iOS icon? If so, this message is correct and telling you that your image isn't big enough.

**Comment by bencooling** [comment]
@haydenbleasel The issue is instead of the generic 'Uncaught, unspecified error event...' I should have got the specific 'Cannot generate anything for ios...' error message. 

I presume the source code isn't handling the error appropriately.

**Comment by haydenbleasel** [comment]
@bencooling Ahhh okay, I understand. I'll look into error handling today if possible.

**Comment by bencooling** [comment]
No dramas. Great job btw.

**Comment by haydenbleasel** [comment]
Hey guys, the version of `favicons` and `gulp-favicons` should fix up all these issues. Open up a new issue if you find something is broken :)
