### ISSUE TITLE
Email issue

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/gulp-favicons#12]
Hi. Excuse for my English. I like your gulp-favicons, but I am a noob and it is impossible to force it to work for me. I do so:
1) I install gulp-favicons
2) Copy in gulpfile.js this:

```
var gulp = require(‘gulp’),
 favicons = require(‘gulp-favicons’);

gulp.task(‘favicon’, function () {
    gulp.src(‘index.html’)
        .pipe(favicons({
            files: { dest: ‘images/‘ },
            settings: { background: ‘#1d1d1d’ }
        }))
        .pipe(gulp.dest(‘./‘));
});
```

3)gulp favicon
4)The terminal (i use windows 8.1) gives out a mistake:

```
C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\index.js:258
                    encodeBase64(source.android, function (error, file) {
                                       ^
TypeError: Cannot read property ‘android’ of null
    at async.parallel.config.data.favicon_generation.favicon_design.ios.master_picture.type (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\n
ode_modules\favicons\index.js:258:40)
    at C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:567:21
    at C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:246:17
    at C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:122:13
    at _each (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:46:13)
    at async.each (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:121:9)
    at _asyncMap (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:245:13)
    at Object.map (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:216:23)
    at _parallel (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:565:20)
    at Object.async.parallel (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:595:9)
    at setIcons (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\index.js:256:19)
    at C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\index.js:29:17
    at fn (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:638:34)
    at Immediate._onImmediate (C:\Users\leshiple\Google Drive\Web\OpenServer\domains\tyr.local\node_modules\gulp-favicons\node_modules\favicons\node_modules\async\lib\async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by finnbuster** [comment]
I'm having this same issue. How do I fix it?

**Comment by wdmtech** [comment]
Same here. Upon inspection, using:

```
// Favicons
gulp.task('favicons', function () {
    gulp.src('source/_layouts/default.html')
        .pipe(favicons({
            files: {
                dest: 'source/images',
            },
            settings: { background: '#1d1d1d' }
        }))
        .pipe(gulp.dest('./'));
});
```

The output of `favicons` is showing that my images are looked for here:
`/Users/stoaty/Dev/my-site/source/_layouts/images/logo.png`
instead of:
`/Users/stoaty/Dev/my-site/source/images/logo.png`

Not sure what's going on here.

**Comment by jitendravyas** [comment]
same issue with me

**Comment by neopostmodern** [comment]
Is any workaround known? Or is the entire package broke?

**Comment by sgarbesi** [comment]
+1

**Comment by sgarbesi** [comment]
@neopostmodern @jitendravyas @wdmtech @finnbuster @haydenbleasel Specify the `src` in the `file` block of the configuration.

```javascript
			.pipe(
				gulpFavicons({
					files: {
						src: path.join(app.config.uri.srcImg, 'favicon.png'),
						dest: path.join(app.config.uri.distImg, 'favicon')
					},

					settings: {
						background: '#ffffff'
					}
				})
			)
```

**Comment by neopostmodern** [comment]
After adding the `src` as in
```
.pipe(favicons({
      files: {
        src: 'app/images/icons/favicon.png',
        dest: 'dist/images/icons/'
      },
      settings: { background: '#000000' }
    }))
```
I now get
```
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at DestroyableTransform.emit (events.js:87:13)
    at DestroyableTransform.onerror (/home/mrssheep/Code/AllNight2/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:107:17)
    at onwriteError (/home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:338:10)
    at onwrite (/home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at WritableState.onwrite (/home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:116:5)
    at afterTransform (/home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:84:5)
    at TransformState.afterTransform (/home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at /home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/index.js:129:28
    at /home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/favicons/index.js:58:31
    at /home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/favicons/node_modules/async/lib/async.js:541:30
    at /home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/favicons/index.js:37:28
    at /home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/favicons/index.js:116:28
    at /home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/favicons/index.js:95:24
    at Object.ConnectManager.handleResponse (/home/mrssheep/Code/AllNight2/node_modules/gulp-favicons/node_modules/favicons/node_modules/node-rest-client/lib/node-rest-client.js:435:5)
```

**Comment by haydenbleasel** [comment]
Hey guys, the version of `favicons` and `gulp-favicons` should fix up all these issues. Open up a new issue if you find something is broken :)
